import { MigrationInterface, QueryRunner } from "typeorm";

export class addNotionAndRefactored1673855797237 implements MigrationInterface {
    name = 'addNotionAndRefactored1673855797237'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` DROP FOREIGN KEY \`m_company_conditions_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` DROP FOREIGN KEY \`todo_update_histories_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`todo_users\` DROP FOREIGN KEY \`todo_users_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`todo_users\` DROP FOREIGN KEY \`todo_users_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`todos\` DROP FOREIGN KEY \`company_id_index\``);
        await queryRunner.query(`ALTER TABLE \`todos\` DROP FOREIGN KEY \`section_id_index\``);
        await queryRunner.query(`ALTER TABLE \`todos\` DROP FOREIGN KEY \`todos_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` DROP FOREIGN KEY \`implemented_todo_apps_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` DROP FOREIGN KEY \`implemented_todo_apps_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` DROP FOREIGN KEY \`todo_app_users_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` DROP FOREIGN KEY \`todo_app_users_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`sections\` DROP FOREIGN KEY \`sections_board_admin_user_id_index\``);
        await queryRunner.query(`ALTER TABLE \`sections\` DROP FOREIGN KEY \`sections_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`sections\` DROP FOREIGN KEY \`sections_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` DROP FOREIGN KEY \`chat_tool_users_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` DROP FOREIGN KEY \`chat_tool_users_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`users_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` DROP FOREIGN KEY \`implemented_chat_tools_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` DROP FOREIGN KEY \`implemented_chat_tools_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`messages_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`messages_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`messages_ibfk_3\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`messages_ibfk_4\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`messages_ibfk_5\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`messages_ibfk_6\``);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` DROP FOREIGN KEY \`line_message_queues_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` DROP FOREIGN KEY \`line_message_queues_ibfk_2\``);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` DROP FOREIGN KEY \`line_message_queues_message_id_index\``);
        await queryRunner.query(`ALTER TABLE \`remind_user_jobs\` DROP FOREIGN KEY \`remind_user_jobs_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` DROP FOREIGN KEY \`reporting_lines_ibfk_1\``);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` DROP FOREIGN KEY \`reporting_lines_ibfk_2\``);
        await queryRunner.query(`DROP INDEX \`company_id\` ON \`m_company_conditions\``);
        await queryRunner.query(`DROP INDEX \`todo_id\` ON \`todo_update_histories\``);
        await queryRunner.query(`DROP INDEX \`todo_id\` ON \`todo_users\``);
        await queryRunner.query(`DROP INDEX \`user_id\` ON \`todo_users\``);
        await queryRunner.query(`DROP INDEX \`todoapp_id_todoapp_reg_id_index\` ON \`todos\``);
        await queryRunner.query(`DROP INDEX \`company_id\` ON \`implemented_todo_apps\``);
        await queryRunner.query(`DROP INDEX \`todoapp_id\` ON \`implemented_todo_apps\``);
        await queryRunner.query(`DROP INDEX \`employee_id\` ON \`todo_app_users\``);
        await queryRunner.query(`DROP INDEX \`todoapp_id\` ON \`todo_app_users\``);
        await queryRunner.query(`DROP INDEX \`todo_app_code_index\` ON \`m_todo_apps\``);
        await queryRunner.query(`DROP INDEX \`board_id_index\` ON \`sections\``);
        await queryRunner.query(`DROP INDEX \`company_id\` ON \`sections\``);
        await queryRunner.query(`DROP INDEX \`todoapp_id\` ON \`sections\``);
        await queryRunner.query(`DROP INDEX \`chat_tool_users_user_id_chattool_id_index\` ON \`chat_tool_users\``);
        await queryRunner.query(`DROP INDEX \`chattool_id\` ON \`chat_tool_users\``);
        await queryRunner.query(`DROP INDEX \`company_id\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`chattool_id\` ON \`implemented_chat_tools\``);
        await queryRunner.query(`DROP INDEX \`company_id\` ON \`implemented_chat_tools\``);
        await queryRunner.query(`DROP INDEX \`chattool_id\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`message_trigger_id\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`message_type_id\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`reply_content_type_id\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`todo_id\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`user_id\` ON \`messages\``);
        await queryRunner.query(`DROP INDEX \`todo_id\` ON \`line_message_queues\``);
        await queryRunner.query(`DROP INDEX \`user_id\` ON \`line_message_queues\``);
        await queryRunner.query(`DROP INDEX \`user_id\` ON \`remind_user_jobs\``);
        await queryRunner.query(`DROP INDEX \`subordinate_user_id\` ON \`reporting_lines\``);
        await queryRunner.query(`DROP INDEX \`superior_user_id\` ON \`reporting_lines\``);
        await queryRunner.query(`CREATE TABLE \`todo_sections\` (\`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP, \`deleted_at\` datetime NULL, \`todo_id\` int NOT NULL, \`section_id\` int NOT NULL, PRIMARY KEY (\`todo_id\`, \`section_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`section_labels\` (\`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP, \`deleted_at\` datetime NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL, \`section_id\` int NOT NULL, \`label_id\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL, UNIQUE INDEX \`REL_e7566dddb9af62f46aeec4bbd3\` (\`section_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`column_names\` (\`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP, \`deleted_at\` datetime NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`section_id\` int NOT NULL, \`label_todo\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL, \`label_section\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL, \`label_is_done\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL, \`label_is_archived\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL, \`label_assignee\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL, \`label_due\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL, \`label_created_at\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL, \`label_created_by\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL, UNIQUE INDEX \`REL_732dfbc7e428de453d1189c464\` (\`section_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`todos\` DROP COLUMN \`section_id\``);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`m_todo_apps\` DROP COLUMN \`update_at\``);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`update_at\``);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`update_at\``);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`m_chat_tools\` DROP COLUMN \`update_at\``);
        await queryRunner.query(`ALTER TABLE \`m_message_types\` DROP COLUMN \`update_at\``);
        await queryRunner.query(`ALTER TABLE \`line_profiles\` DROP COLUMN \`update_at\``);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` ADD \`deleted_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` ADD \`deleted_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`todos\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`todos\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`todos\` ADD \`deleted_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` ADD \`deleted_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` ADD \`deleted_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`m_todo_apps\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` ADD \`deleted_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` ADD \`deleted_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`m_chat_tools\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`m_message_types\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` ADD \`deleted_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`line_profiles\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`remind_user_jobs\` ADD \`deleted_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` ADD \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` ADD \`deleted_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` ADD PRIMARY KEY (\`todo_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` ADD PRIMARY KEY (\`company_id\`, \`todoapp_id\`)`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` ADD PRIMARY KEY (\`employee_id\`, \`todoapp_id\`)`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` ADD PRIMARY KEY (\`user_id\`, \`chattool_id\`)`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` ADD PRIMARY KEY (\`company_id\`, \`chattool_id\`)`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` ADD PRIMARY KEY (\`superior_user_id\`, \`subordinate_user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` CHANGE \`company_id\` \`company_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` CHANGE \`remind_before_days\` \`remind_before_days\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` CHANGE \`todo_id\` \`todo_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` CHANGE \`is_done\` \`is_done\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` CHANGE \`todoapp_reg_updated_at\` \`todoapp_reg_updated_at\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` CHANGE \`todo_id\` \`todo_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` CHANGE \`user_id\` \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`todos\` CHANGE \`todoapp_reg_created_at\` \`todoapp_reg_created_at\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`todos\` CHANGE \`is_done\` \`is_done\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`todos\` CHANGE \`is_reminded\` \`is_reminded\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`todos\` CHANGE \`delayed_count\` \`delayed_count\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`todos\` CHANGE \`is_closed\` \`is_closed\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`todos\` CHANGE \`reminded_count\` \`reminded_count\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` CHANGE \`company_id\` \`company_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` CHANGE \`todoapp_id\` \`todoapp_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` CHANGE \`employee_id\` \`employee_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` CHANGE \`todoapp_id\` \`todoapp_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`m_todo_apps\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`sections\` CHANGE \`name\` \`name\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` CHANGE \`user_id\` \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` CHANGE \`chattool_id\` \`chattool_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`companies\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`admin_user_id\``);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`admin_user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`companies\` CHANGE \`is_demo\` \`is_demo\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` CHANGE \`company_id\` \`company_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` CHANGE \`chattool_id\` \`chattool_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`m_chat_tools\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`m_message_types\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`is_from_user\` \`is_from_user\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`message_token\` \`message_token\` text COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`is_openned\` \`is_openned\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`is_replied\` \`is_replied\` tinyint NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`body\` \`body\` text COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`remind_type\` \`remind_type\` tinyint(1) NOT NULL COMMENT '0: リマインドでない, 1: 期日に対するリマインド, 2: 担当者未設定に対するリマインド, 3: 期日未設定に対するリマインド, 4: 担当者・期日未設定に対するリマインド' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` CHANGE \`todo_id\` \`todo_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` CHANGE \`user_id\` \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` CHANGE \`status\` \`status\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` ADD UNIQUE INDEX \`IDX_df8d608ee34ce8816a96a80502\` (\`message_id\`)`);
        await queryRunner.query(`ALTER TABLE \`line_profiles\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`remind_user_jobs\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`remind_user_jobs\` CHANGE \`updated_at\` \`updated_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` CHANGE \`superior_user_id\` \`superior_user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` CHANGE \`subordinate_user_id\` \`subordinate_user_id\` int NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_df8d608ee34ce8816a96a80502\` ON \`line_message_queues\` (\`message_id\`)`);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` ADD CONSTRAINT \`FK_82cfd13319a212625e508cb026c\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` ADD CONSTRAINT \`FK_ddfae091efe3d48836ffe558560\` FOREIGN KEY (\`todo_id\`) REFERENCES \`todos\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` ADD CONSTRAINT \`FK_1a382f881da27a070205677099f\` FOREIGN KEY (\`todo_id\`) REFERENCES \`todos\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` ADD CONSTRAINT \`FK_aec5d613b8a2bba3e2834713365\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`todo_sections\` ADD CONSTRAINT \`FK_10c84d07ac8e4247465c6e8e46a\` FOREIGN KEY (\`todo_id\`) REFERENCES \`todos\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`todo_sections\` ADD CONSTRAINT \`FK_46b78aa9cdad0aa3c0f47a0cfb8\` FOREIGN KEY (\`section_id\`) REFERENCES \`sections\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`todos\` ADD CONSTRAINT \`FK_00d7d5ab26f415f0745417dd4d3\` FOREIGN KEY (\`todoapp_id\`) REFERENCES \`m_todo_apps\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`todos\` ADD CONSTRAINT \`FK_dc52f169de9167b7d13ed86d08f\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` ADD CONSTRAINT \`FK_0643af4c605a5300c9246219e84\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` ADD CONSTRAINT \`FK_f7aa29458db9cdf319616a8a7ef\` FOREIGN KEY (\`todoapp_id\`) REFERENCES \`m_todo_apps\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` ADD CONSTRAINT \`FK_47d0aa465190d3960230313b6ad\` FOREIGN KEY (\`employee_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` ADD CONSTRAINT \`FK_06379bc9d1e2038db60a530013c\` FOREIGN KEY (\`todoapp_id\`) REFERENCES \`m_todo_apps\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`section_labels\` ADD CONSTRAINT \`FK_e7566dddb9af62f46aeec4bbd3a\` FOREIGN KEY (\`section_id\`) REFERENCES \`sections\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`sections\` ADD CONSTRAINT \`FK_9692e8539317d6ae89cfcedd21e\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`sections\` ADD CONSTRAINT \`FK_4d92452c9612ab582677cab1946\` FOREIGN KEY (\`todoapp_id\`) REFERENCES \`m_todo_apps\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`sections\` ADD CONSTRAINT \`FK_1c0bfa8097263834f1ee123f4c2\` FOREIGN KEY (\`board_admin_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` ADD CONSTRAINT \`FK_f8f2b91512e8764ce8c354ff408\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` ADD CONSTRAINT \`FK_47a0ec2029b78a6763d92101b6a\` FOREIGN KEY (\`chattool_id\`) REFERENCES \`m_chat_tools\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_7ae6334059289559722437bcc1c\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD CONSTRAINT \`FK_d8c5ee51b5be0550962a5fb95ae\` FOREIGN KEY (\`admin_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` ADD CONSTRAINT \`FK_0b16e5d0a447cd2ac75e6dfe044\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` ADD CONSTRAINT \`FK_03b88a97a4e616464ffaed4c272\` FOREIGN KEY (\`chattool_id\`) REFERENCES \`m_chat_tools\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`column_names\` ADD CONSTRAINT \`FK_732dfbc7e428de453d1189c464d\` FOREIGN KEY (\`section_id\`) REFERENCES \`sections\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_bddc671662390b17a2df6815075\` FOREIGN KEY (\`message_type_id\`) REFERENCES \`m_message_types\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_830a3c1d92614d1495418c46736\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_66fd0b962f352df94a0916a7153\` FOREIGN KEY (\`chattool_id\`) REFERENCES \`m_chat_tools\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_d9f251c27b8d48c196d8946a419\` FOREIGN KEY (\`todo_id\`) REFERENCES \`todos\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` ADD CONSTRAINT \`FK_4154291725b583001e8ef892a9d\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` ADD CONSTRAINT \`FK_ab3eaead33ae9b70efba9bbf95a\` FOREIGN KEY (\`todo_id\`) REFERENCES \`todos\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` ADD CONSTRAINT \`FK_df8d608ee34ce8816a96a805022\` FOREIGN KEY (\`message_id\`) REFERENCES \`messages\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`remind_user_jobs\` ADD CONSTRAINT \`FK_63db03d83b05fc0432e206a0f1b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE RESTRICT`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`remind_user_jobs\` DROP FOREIGN KEY \`FK_63db03d83b05fc0432e206a0f1b\``);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` DROP FOREIGN KEY \`FK_df8d608ee34ce8816a96a805022\``);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` DROP FOREIGN KEY \`FK_ab3eaead33ae9b70efba9bbf95a\``);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` DROP FOREIGN KEY \`FK_4154291725b583001e8ef892a9d\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_d9f251c27b8d48c196d8946a419\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_66fd0b962f352df94a0916a7153\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_830a3c1d92614d1495418c46736\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_bddc671662390b17a2df6815075\``);
        await queryRunner.query(`ALTER TABLE \`column_names\` DROP FOREIGN KEY \`FK_732dfbc7e428de453d1189c464d\``);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` DROP FOREIGN KEY \`FK_03b88a97a4e616464ffaed4c272\``);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` DROP FOREIGN KEY \`FK_0b16e5d0a447cd2ac75e6dfe044\``);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP FOREIGN KEY \`FK_d8c5ee51b5be0550962a5fb95ae\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_7ae6334059289559722437bcc1c\``);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` DROP FOREIGN KEY \`FK_47a0ec2029b78a6763d92101b6a\``);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` DROP FOREIGN KEY \`FK_f8f2b91512e8764ce8c354ff408\``);
        await queryRunner.query(`ALTER TABLE \`sections\` DROP FOREIGN KEY \`FK_1c0bfa8097263834f1ee123f4c2\``);
        await queryRunner.query(`ALTER TABLE \`sections\` DROP FOREIGN KEY \`FK_4d92452c9612ab582677cab1946\``);
        await queryRunner.query(`ALTER TABLE \`sections\` DROP FOREIGN KEY \`FK_9692e8539317d6ae89cfcedd21e\``);
        await queryRunner.query(`ALTER TABLE \`section_labels\` DROP FOREIGN KEY \`FK_e7566dddb9af62f46aeec4bbd3a\``);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` DROP FOREIGN KEY \`FK_06379bc9d1e2038db60a530013c\``);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` DROP FOREIGN KEY \`FK_47d0aa465190d3960230313b6ad\``);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` DROP FOREIGN KEY \`FK_f7aa29458db9cdf319616a8a7ef\``);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` DROP FOREIGN KEY \`FK_0643af4c605a5300c9246219e84\``);
        await queryRunner.query(`ALTER TABLE \`todos\` DROP FOREIGN KEY \`FK_dc52f169de9167b7d13ed86d08f\``);
        await queryRunner.query(`ALTER TABLE \`todos\` DROP FOREIGN KEY \`FK_00d7d5ab26f415f0745417dd4d3\``);
        await queryRunner.query(`ALTER TABLE \`todo_sections\` DROP FOREIGN KEY \`FK_46b78aa9cdad0aa3c0f47a0cfb8\``);
        await queryRunner.query(`ALTER TABLE \`todo_sections\` DROP FOREIGN KEY \`FK_10c84d07ac8e4247465c6e8e46a\``);
        await queryRunner.query(`ALTER TABLE \`todo_users\` DROP FOREIGN KEY \`FK_aec5d613b8a2bba3e2834713365\``);
        await queryRunner.query(`ALTER TABLE \`todo_users\` DROP FOREIGN KEY \`FK_1a382f881da27a070205677099f\``);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` DROP FOREIGN KEY \`FK_ddfae091efe3d48836ffe558560\``);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` DROP FOREIGN KEY \`FK_82cfd13319a212625e508cb026c\``);
        await queryRunner.query(`DROP INDEX \`REL_df8d608ee34ce8816a96a80502\` ON \`line_message_queues\``);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` CHANGE \`subordinate_user_id\` \`subordinate_user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` CHANGE \`superior_user_id\` \`superior_user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`remind_user_jobs\` CHANGE \`updated_at\` \`updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`remind_user_jobs\` CHANGE \`created_at\` \`created_at\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`line_profiles\` CHANGE \`created_at\` \`created_at\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` DROP INDEX \`IDX_df8d608ee34ce8816a96a80502\``);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` CHANGE \`status\` \`status\` tinyint(1) NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` CHANGE \`todo_id\` \`todo_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` CHANGE \`created_at\` \`created_at\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`remind_type\` \`remind_type\` tinyint(1) NULL COMMENT '0: リマインドでない, 1: 期日に対するリマインド, 2: 担当者未設定に対するリマインド, 3: 期日未設定に対するリマインド, 4: 担当者・期日未設定に対するリマインド' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`body\` \`body\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`is_replied\` \`is_replied\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`is_openned\` \`is_openned\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`message_token\` \`message_token\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`messages\` CHANGE \`is_from_user\` \`is_from_user\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`m_message_types\` CHANGE \`created_at\` \`created_at\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`m_chat_tools\` CHANGE \`created_at\` \`created_at\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` CHANGE \`chattool_id\` \`chattool_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` CHANGE \`company_id\` \`company_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`companies\` CHANGE \`is_demo\` \`is_demo\` tinyint(1) NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`admin_user_id\``);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`admin_user_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`companies\` CHANGE \`created_at\` \`created_at\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`created_at\` \`created_at\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` CHANGE \`chattool_id\` \`chattool_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`sections\` CHANGE \`name\` \`name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`m_todo_apps\` CHANGE \`created_at\` \`created_at\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` CHANGE \`todoapp_id\` \`todoapp_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` CHANGE \`employee_id\` \`employee_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` CHANGE \`todoapp_id\` \`todoapp_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` CHANGE \`company_id\` \`company_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`todos\` CHANGE \`reminded_count\` \`reminded_count\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`todos\` CHANGE \`is_closed\` \`is_closed\` tinyint(1) NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`todos\` CHANGE \`delayed_count\` \`delayed_count\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`todos\` CHANGE \`is_reminded\` \`is_reminded\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`todos\` CHANGE \`is_done\` \`is_done\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`todos\` CHANGE \`todoapp_reg_created_at\` \`todoapp_reg_created_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` CHANGE \`todo_id\` \`todo_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` CHANGE \`created_at\` \`created_at\` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` CHANGE \`todoapp_reg_updated_at\` \`todoapp_reg_updated_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` CHANGE \`is_done\` \`is_done\` tinyint(1) NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` CHANGE \`todo_id\` \`todo_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` CHANGE \`remind_before_days\` \`remind_before_days\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` CHANGE \`company_id\` \`company_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`remind_user_jobs\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`line_profiles\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`m_message_types\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`m_chat_tools\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`m_todo_apps\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`todos\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`todos\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`todos\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`todo_users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`line_profiles\` ADD \`update_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`m_message_types\` ADD \`update_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`m_chat_tools\` ADD \`update_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`update_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`update_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`m_todo_apps\` ADD \`update_at\` datetime NULL ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`todos\` ADD \`section_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`DROP INDEX \`REL_732dfbc7e428de453d1189c464\` ON \`column_names\``);
        await queryRunner.query(`DROP TABLE \`column_names\``);
        await queryRunner.query(`DROP INDEX \`REL_e7566dddb9af62f46aeec4bbd3\` ON \`section_labels\``);
        await queryRunner.query(`DROP TABLE \`section_labels\``);
        await queryRunner.query(`DROP TABLE \`todo_sections\``);
        await queryRunner.query(`CREATE INDEX \`superior_user_id\` ON \`reporting_lines\` (\`superior_user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`subordinate_user_id\` ON \`reporting_lines\` (\`subordinate_user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`user_id\` ON \`remind_user_jobs\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`user_id\` ON \`line_message_queues\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`todo_id\` ON \`line_message_queues\` (\`todo_id\`)`);
        await queryRunner.query(`CREATE INDEX \`user_id\` ON \`messages\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`todo_id\` ON \`messages\` (\`todo_id\`)`);
        await queryRunner.query(`CREATE INDEX \`reply_content_type_id\` ON \`messages\` (\`reply_content_type_id\`)`);
        await queryRunner.query(`CREATE INDEX \`message_type_id\` ON \`messages\` (\`message_type_id\`)`);
        await queryRunner.query(`CREATE INDEX \`message_trigger_id\` ON \`messages\` (\`message_trigger_id\`)`);
        await queryRunner.query(`CREATE INDEX \`chattool_id\` ON \`messages\` (\`chattool_id\`)`);
        await queryRunner.query(`CREATE INDEX \`company_id\` ON \`implemented_chat_tools\` (\`company_id\`)`);
        await queryRunner.query(`CREATE INDEX \`chattool_id\` ON \`implemented_chat_tools\` (\`chattool_id\`)`);
        await queryRunner.query(`CREATE INDEX \`company_id\` ON \`users\` (\`company_id\`)`);
        await queryRunner.query(`CREATE INDEX \`chattool_id\` ON \`chat_tool_users\` (\`chattool_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`chat_tool_users_user_id_chattool_id_index\` ON \`chat_tool_users\` (\`user_id\`, \`chattool_id\`)`);
        await queryRunner.query(`CREATE INDEX \`todoapp_id\` ON \`sections\` (\`todoapp_id\`)`);
        await queryRunner.query(`CREATE INDEX \`company_id\` ON \`sections\` (\`company_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`board_id_index\` ON \`sections\` (\`board_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`todo_app_code_index\` ON \`m_todo_apps\` (\`todo_app_code\`)`);
        await queryRunner.query(`CREATE INDEX \`todoapp_id\` ON \`todo_app_users\` (\`todoapp_id\`)`);
        await queryRunner.query(`CREATE INDEX \`employee_id\` ON \`todo_app_users\` (\`employee_id\`)`);
        await queryRunner.query(`CREATE INDEX \`todoapp_id\` ON \`implemented_todo_apps\` (\`todoapp_id\`)`);
        await queryRunner.query(`CREATE INDEX \`company_id\` ON \`implemented_todo_apps\` (\`company_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`todoapp_id_todoapp_reg_id_index\` ON \`todos\` (\`todoapp_id\`, \`todoapp_reg_id\`)`);
        await queryRunner.query(`CREATE INDEX \`user_id\` ON \`todo_users\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`todo_id\` ON \`todo_users\` (\`todo_id\`)`);
        await queryRunner.query(`CREATE INDEX \`todo_id\` ON \`todo_update_histories\` (\`todo_id\`)`);
        await queryRunner.query(`CREATE INDEX \`company_id\` ON \`m_company_conditions\` (\`company_id\`)`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` ADD CONSTRAINT \`reporting_lines_ibfk_2\` FOREIGN KEY (\`subordinate_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reporting_lines\` ADD CONSTRAINT \`reporting_lines_ibfk_1\` FOREIGN KEY (\`superior_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`remind_user_jobs\` ADD CONSTRAINT \`remind_user_jobs_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` ADD CONSTRAINT \`line_message_queues_message_id_index\` FOREIGN KEY (\`message_id\`) REFERENCES \`messages\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` ADD CONSTRAINT \`line_message_queues_ibfk_2\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`line_message_queues\` ADD CONSTRAINT \`line_message_queues_ibfk_1\` FOREIGN KEY (\`todo_id\`) REFERENCES \`todos\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`messages_ibfk_6\` FOREIGN KEY (\`reply_content_type_id\`) REFERENCES \`m_reply_content_types\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`messages_ibfk_5\` FOREIGN KEY (\`todo_id\`) REFERENCES \`todos\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`messages_ibfk_4\` FOREIGN KEY (\`chattool_id\`) REFERENCES \`m_chat_tools\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`messages_ibfk_3\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`messages_ibfk_2\` FOREIGN KEY (\`message_trigger_id\`) REFERENCES \`m_message_triggers\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`messages_ibfk_1\` FOREIGN KEY (\`message_type_id\`) REFERENCES \`m_message_types\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` ADD CONSTRAINT \`implemented_chat_tools_ibfk_2\` FOREIGN KEY (\`chattool_id\`) REFERENCES \`m_chat_tools\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`implemented_chat_tools\` ADD CONSTRAINT \`implemented_chat_tools_ibfk_1\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`users_ibfk_1\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` ADD CONSTRAINT \`chat_tool_users_ibfk_2\` FOREIGN KEY (\`chattool_id\`) REFERENCES \`m_chat_tools\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`chat_tool_users\` ADD CONSTRAINT \`chat_tool_users_ibfk_1\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sections\` ADD CONSTRAINT \`sections_ibfk_2\` FOREIGN KEY (\`todoapp_id\`) REFERENCES \`m_todo_apps\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sections\` ADD CONSTRAINT \`sections_ibfk_1\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sections\` ADD CONSTRAINT \`sections_board_admin_user_id_index\` FOREIGN KEY (\`board_admin_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` ADD CONSTRAINT \`todo_app_users_ibfk_2\` FOREIGN KEY (\`todoapp_id\`) REFERENCES \`m_todo_apps\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`todo_app_users\` ADD CONSTRAINT \`todo_app_users_ibfk_1\` FOREIGN KEY (\`employee_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` ADD CONSTRAINT \`implemented_todo_apps_ibfk_2\` FOREIGN KEY (\`todoapp_id\`) REFERENCES \`m_todo_apps\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`implemented_todo_apps\` ADD CONSTRAINT \`implemented_todo_apps_ibfk_1\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`todos\` ADD CONSTRAINT \`todos_ibfk_1\` FOREIGN KEY (\`todoapp_id\`) REFERENCES \`m_todo_apps\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`todos\` ADD CONSTRAINT \`section_id_index\` FOREIGN KEY (\`section_id\`) REFERENCES \`sections\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`todos\` ADD CONSTRAINT \`company_id_index\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` ADD CONSTRAINT \`todo_users_ibfk_2\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`todo_users\` ADD CONSTRAINT \`todo_users_ibfk_1\` FOREIGN KEY (\`todo_id\`) REFERENCES \`todos\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`todo_update_histories\` ADD CONSTRAINT \`todo_update_histories_ibfk_1\` FOREIGN KEY (\`todo_id\`) REFERENCES \`todos\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`m_company_conditions\` ADD CONSTRAINT \`m_company_conditions_ibfk_1\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
