runtime: nodejs16 # or another supported version

instance_class: F1

env_variables:
  PORT: 8080
  DB_HOST: 10.124.160.3
  DB_PORT: 3306
  DB_DATABASE: angle-dev-db
  DB_USERNAME: root
  DB_PASSWORD: ''

  TRELLO_API_URL: https://api.trello.com

  MICROSOFT_AAD_ENDPOINT: https://login.microsoftonline.com
  MICROSOFT_GRAPH_API_VERSION: v1.0
  MICROSOFT_GRAPH_API_ENDPOINT: https://graph.microsoft.com
  MICROSOFT_GRAPH_API_URL: ${MICROSOFT_GRAPH_API_ENDPOINT}/${MICROSOFT_GRAPH_API_VERSION}

  LINE_CHANNEL_ACCESS_TOKEN: r7mqQw5Ob4sVo2g2Ud5xPnORryQV140P5X6gMlLeMpU3OboLX5IMM//8WKYgKM8vVXqw3Gocr6CGOMVUputAX6BxWXlN17ySjHOrnsYAGHSHuUXeZOeLKEOsTwADMtnU2U/4+dYnfJBvZEl0Jjf4twdB04t89/1O/w1cDnyilFU=
  LINE_CHANNEL_SECRET: f7b05245bea6a4d07aa55483f4c6f533

vpc_access_connector:
 name: projects/rize-angel-dev/locations/asia-northeast2/connectors/connect-to-mysql
 egress_setting: all-traffic

