runtime: nodejs16 # or another supported version

instance_class: F1

env_variables:
  PORT: 8080
  DB_PORT: 3306

  TRELLO_API_URL: https://api.trello.com

  MICROSOFT_AAD_ENDPOINT: https://login.microsoftonline.com
  MICROSOFT_GRAPH_API_VERSION: v1.0
  MICROSOFT_GRAPH_API_ENDPOINT: https://graph.microsoft.com
  MICROSOFT_GRAPH_API_URL: ${MICROSOFT_GRAPH_API_ENDPOINT}/${MICROSOFT_GRAPH_API_VERSION}

automatic_scaling:
  min_idle_instances: 1

inbound_services:
  - warmup