steps:
  - id: Install packages
    name: node:16
    entrypoint: yarn
    args:
      - install
  - id: Build
    name: node:16
    entrypoint: yarn
    args:
      - build
  - id: Generate app.yaml with decrypted secrets
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -eEuo
      - pipefail
      - -c
      - |-
        cat <<EOF > ./app.yaml
        runtime: nodejs16 # or another supported version
        handlers:
          - url: /
            static_dir: dist
        instance_class: F1
        env_variables:
          HOST: $_HOST
          PORT: 8080
          ENV: $_ENV
          DB_HOST: $_DB_HOST
          DB_PORT: 3306
          DB_DATABASE: $_DB_DATABASE
          DB_USERNAME: $_DB_USERNAME
          DB_PASSWORD: $$DB_PASSWORD
          TRELLO_API_URL: https://api.trello.com
          MICROSOFT_AAD_ENDPOINT: https://login.microsoftonline.com
          MICROSOFT_GRAPH_API_VERSION: v1.0
          MICROSOFT_GRAPH_API_ENDPOINT: https://graph.microsoft.com
          MICROSOFT_GRAPH_API_URL: https://graph.microsoft.com/v1.0
          MICROSOFT_CLIENT_ID: $$MICROSOFT_CLIENT_ID
          MICROSOFT_CLIENT_SECRET: $$MICROSOFT_CLIENT_SECRET
          LINE_CHANNEL_ACCESS_TOKEN: $$LINE_CHANNEL_ACCESS_TOKEN
          LINE_CHANNEL_SECRET: $$LINE_CHANNEL_SECRET
        vpc_access_connector:
          name: projects/$PROJECT_ID/locations/asia-northeast2/connectors/connect-to-mysql
          egress_setting: private-ranges-only
        automatic_scaling:
          min_idle_instances: 1
        inbound_services:
          - warmup
        EOF
    secretEnv:
      - DB_PASSWORD
      - MICROSOFT_CLIENT_ID
      - MICROSOFT_CLIENT_SECRET
      - LINE_CHANNEL_ACCESS_TOKEN
      - LINE_CHANNEL_SECRET
  - id: Deploy app
    name: gcr.io/cloud-builders/gcloud
    args:
      - app
      - deploy
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/DB_PASSWORD/versions/latest
      env: DB_PASSWORD
    - versionName: projects/$PROJECT_NUMBER/secrets/MICROSOFT_CLIENT_ID/versions/latest
      env: MICROSOFT_CLIENT_ID
    - versionName: projects/$PROJECT_NUMBER/secrets/MICROSOFT_CLIENT_SECRET/versions/latest
      env: MICROSOFT_CLIENT_SECRET
    - versionName: projects/$PROJECT_NUMBER/secrets/LINE_CHANNEL_ACCESS_TOKEN/versions/latest
      env: LINE_CHANNEL_ACCESS_TOKEN
    - versionName: projects/$PROJECT_NUMBER/secrets/LINE_CHANNEL_SECRET/versions/latest
      env: LINE_CHANNEL_SECRET
timeout: 1600s