steps:
  - id: decrypt-key
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -eEuo
      - pipefail
      - -c
      - |-
        cat <<EOF > ./app.env.yaml
        env_variables:
          HOST: $_HOST
          ENV: $_ENV
          DB_HOST: $_DB_HOST
          DB_DATABASE: $_DB_DATABASE
          DB_USERNAME: $_DB_USERNAME
          DB_PASSWORD: $$DB_PASSWORD
          MICROSOFT_CLIENT_ID: $$MICROSOFT_CLIENT_ID
          MICROSOFT_CLIENT_SECRET: $$MICROSOFT_CLIENT_SECRET
          LINE_CHANNEL_ACCESS_TOKEN: $$LINE_CHANNEL_ACCESS_TOKEN
          LINE_CHANNEL_SECRET: $$LINE_CHANNEL_SECRET
        vpc_access_connector:
          name: projects/$PROJECT_ID/locations/asia-northeast2/connectors/connect-to-mysql
          egress_setting: private-ranges-only
        includes:
          - app.yaml
        EOF
    secretEnv:
      - DB_PASSWORD
      - MICROSOFT_CLIENT_ID
      - MICROSOFT_CLIENT_SECRET
      - LINE_CHANNEL_ACCESS_TOKEN
      - LINE_CHANNEL_SECRET
  - id: app-deploy
    name: gcr.io/cloud-builders/gcloud
    args:
      - app
      - deploy
      - app.env.yaml
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/DB_PASSWORD/versions/latest
      env: DB_PASSWORD
    - versionName: projects/$PROJECT_NUMBER/secrets/MICROSOFT_CLIENT_ID/versions/latest
      env: MICROSOFT_CLIENT_ID
    - versionName: projects/$PROJECT_NUMBER/secrets/MICROSOFT_CLIENT_SECRET/versions/latest
      env: MICROSOFT_CLIENT_SECRET
    - versionName: projects/$PROJECT_NUMBER/secrets/LINE_CHANNEL_ACCESS_TOKEN/versions/latest
      env: LINE_CHANNEL_ACCESS_TOKEN
    - versionName: projects/$PROJECT_NUMBER/secrets/LINE_CHANNEL_SECRET/versions/latest
      env: LINE_CHANNEL_SECRET
timeout: 1600s