services:
  api:
    image: node:16.15.0-alpine
    tty: true
    volumes:
      - ./:/app
      - api-data:/usr/app/node_modules
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    working_dir: "/app"
    command: sh -c "yarn install && yarn dev:https"

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: angel-local
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/my.cnf
    command: mysqld

  swagger:
    image: swaggerapi/swagger-ui
    container_name: "swagger"
    ports:
      - "8001:8080"
    volumes:
      - ./docker/swagger/openapi.yaml:/openapi.yaml
    environment:
      API_URL: openapi.yaml
      SWAGGER_JSON: /openapi.yaml

volumes:
  api-data:
  db-data:
